// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQFM_sLI12WSDAV8wOpIVbQAgoo7wqsv4',
    appId: '1:730615818137:web:6117b0ce353ba8a68dd508',
    messagingSenderId: '730615818137',
    projectId: 'mood-tracker-4dfad',
    authDomain: 'mood-tracker-4dfad.firebaseapp.com',
    storageBucket: 'mood-tracker-4dfad.firebasestorage.app',
    measurementId: 'G-F7D7DYMKMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkhdVQF2snjyn_L_KZJAyTd8ME2L4D-YM',
    appId: '1:730615818137:android:7dff63a44fa9fb8b8dd508',
    messagingSenderId: '730615818137',
    projectId: 'mood-tracker-4dfad',
    storageBucket: 'mood-tracker-4dfad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW5FsYuS0SfsppW_VqAIrUpI0-6hHrW2Y',
    appId: '1:730615818137:ios:8eac6a9dc5bc270e8dd508',
    messagingSenderId: '730615818137',
    projectId: 'mood-tracker-4dfad',
    storageBucket: 'mood-tracker-4dfad.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW5FsYuS0SfsppW_VqAIrUpI0-6hHrW2Y',
    appId: '1:730615818137:ios:8eac6a9dc5bc270e8dd508',
    messagingSenderId: '730615818137',
    projectId: 'mood-tracker-4dfad',
    storageBucket: 'mood-tracker-4dfad.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQFM_sLI12WSDAV8wOpIVbQAgoo7wqsv4',
    appId: '1:730615818137:web:cfe89bf3b93de9aa8dd508',
    messagingSenderId: '730615818137',
    projectId: 'mood-tracker-4dfad',
    authDomain: 'mood-tracker-4dfad.firebaseapp.com',
    storageBucket: 'mood-tracker-4dfad.firebasestorage.app',
    measurementId: 'G-EHH67S3E0M',
  );
}
